routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\CustomerController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::namespace('Admin')->group(function () {
    Route::group(['middleware' => 'auth', 'prefix' => 'Admin', 'as' => 'Admin.'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

        #User
        Route::get('/users', 'UserController@index')->name('users.index');
        Route::get('/users/add', 'UserController@create')->name('users.add');
        Route::post('/users/store', 'UserController@store')->name('users.store');
        Route::get('/users/edit/{id}', 'UserController@edit')->name('users.edit');
        Route::put('/users/update/{id}', 'UserController@update')->name('users.update');
        Route::get('/users/detail/{id}', 'UserController@show')->name('users.detail');
        Route::delete('/users/delete/{id}', 'UserController@destroy')->name('users.destroy');


        #account shopee
        Route::get('/user-shopee/add/{id}', 'UserController@create_account')->name('users_shopee.create_account');
        Route::post('/user-shopee/store', 'UserController@store_account')->name('users_shopee.store_account');
        Route::delete('/user-shopee/destroy/{id}', 'UserController@destroy_account')->name('users_shopee.destroy_account');
        Route::get('/user-shopee/edit/{id}', 'UserController@edit_account')->name('users_shopee.edit_account');
        Route::put('/user-shopee/update/{id}', 'UserController@update_account')->name('users_shopee.update_account');
    });
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Customer;
use App\Models\Session;
use App\Models\UserShopee;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use DataTables;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $todays = date("Y-m-d");
        $users = Customer::select();
        if($request->ajax()) {
            return DataTables::eloquent($users)
            ->addIndexColumn()
            ->addColumn('activationAccount', function($user) {
                return $user->jumlah_user;
            })
            ->addColumn('formattedDate', function($user) {
                return Carbon::parse(date('d M Y', strtotime($user->exp_date)))->translatedFormat('d M Y');
            })
            ->addColumn('createdAt', function($user) {
                return Carbon::parse(date('d M Y', strtotime($user->reg_date)))->translatedFormat('d M Y');
            })
            ->addColumn('status', function($user) {
                $expired = $user->exp_date;
                $todays = date("Y-m-d");
                if($todays > $expired) {
                    return '<h6><span class="badge badge-danger">Expired</span></h6>';
                } else {
                    return '<h6><span class="badge badge-success">Active</span></h6>';
                }
            })
            ->addColumn('action', function($user) {
                //  action="{{ route('blog.destroy', $blog->id) }}"
                $html = '<form onsubmit="return confirm("Apakah Anda Yakin ?");" action="'.route('Admin.users.destroy', $user->user_id).'" method="POST">
                            <a href="'.route('Admin.users.detail', $user->user_id).'" class="btn btn-sm btn-info">Detail</a>
                            <a href="'.route('Admin.users.edit', $user->user_id).'" class="btn btn-sm btn-dark">Edit</a>
                            <input type="hidden" name="_token" value="'. csrf_token() .'">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>';
                return $html;
            })
            ->rawColumns(['status', 'action'])
            ->toJson();
        }
        return view('admin.user.index');
    }

    public function create()
    {
        return view('admin.user.add');
    }

    public function store(Request $request)
    {
        $validator = $request->validate([
            'username' => 'required|min:3|unique:user,username',
            'password' => 'required|min:5',
        ]);

        $formattedDate = date("Y-m-d", strtotime($request->expiredate));
        $hashed = md5($request->password);

        $account = Customer::create([
            'username' => $request->username,
            'password' => $hashed,
            'exp_date' => $formattedDate,
            'reg_date' => Carbon::parse(date("Y-m-d")),
            'jumlah_user' => $request->jumlah_user
        ]);

        $session = new Session();
        $session->user_id = $account->user_id;
        $session->save();

        return redirect()->route('Admin.users.index')->with('success', 'Account added');
    }

    public function show(Request $request, $id)
    {
        $user_shopee = UserShopee::where('user_id', $id)->get();
        $customer = Customer::find($id);

        if($request->ajax()) {
            $user_shopee = UserShopee::where('user_id', $id);

            return DataTables::eloquent($user_shopee)
            ->addIndexColumn()
            ->addColumn('shopee_account', function($user_shopee) {
                return $user_shopee->shopee_account;
            })
            ->addColumn('action', function($user_shopee) {
                //  action="{{ route('blog.destroy', $blog->id) }}"
                $html = '<form onsubmit="return confirm("Apakah Anda Yakin ?");" action="'.route('Admin.users_shopee.destroy_account', $user_shopee->id).'" method="POST">
                            <a href="'.route('Admin.users_shopee.edit_account', $user_shopee->id).'" class="btn btn-sm btn-dark">Edit</a>
                            <input type="hidden" name="_token" value="'. csrf_token() .'">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>';
                return $html;
            })
            ->rawColumns(['status', 'action'])
            ->toJson();
        }
        return view('admin.user.detail', compact('user_shopee', 'customer'));
    }

    public function edit($id)
    {
        $user_data = Customer::findOrFail($id);
        return view('admin.user.edit', compact('user_data'));
    }

    public function update(Request $request, $id)
    {
        $formattedDate = date("Y-m-d", strtotime($request->editdate));
        Customer::find($id)->update([
            'username' => $request->username,
            'exp_date' => $formattedDate,
            'jumlah_user' => $request->jumlah_user
        ]);
        return redirect()->route('Admin.users.index')->with('success', 'Customer update');
    }

    public function destroy($id)
    {
        Customer::find($id)->delete();
        return redirect()->route('Admin.users.index')->with('success', 'Customer deleted');
    }

    public function create_account($id)
    {
        $customer = Customer::find($id);
        return view('admin.account_shopee.add', compact('customer'));
    }

    public function store_account(Request $request)
    {
        $user = Customer::where('username', $request->username)->first();
        $get_shopee_account = UserShopee::where('user_id', $user->user_id)->get();

        if (count($get_shopee_account) >= $user->jumlah_user) {
            return redirect()->route('Admin.users.detail', $user->user_id)->with('error', 'Account Shopee Telah Mencapai Batas Maksimum');
        }else{
            $shopee_account = UserShopee::create([
                'user_id' => $user->user_id,
                'shopee_account' => $request->shopee_account,
            ]);
        }

        return redirect()->route('Admin.users.detail', $user->user_id)->with('success', 'Account Shopee added');
    }

    public function destroy_account($id)
    {
        $user_shopee = UserShopee::find($id);
        $user = Customer::find($user_shopee->user_id);

        $user_shopee->delete();
        return redirect()->route('Admin.users.detail', $user->user_id)->with('success', 'Customer deleted');
    }

    public function edit_account($id)
    {
        $user_shopee = UserShopee::where('id', $id)->first();
        $customer = Customer::find($user_shopee->user_id);

        return view('admin.account_shopee.edit', compact('user_shopee', 'customer'));
    }

    public function update_account(Request $request, $id)
    {
        $user_shopee = UserShopee::find($id);
        $customer = Customer::find($user_shopee->user_id);

        $user_shopee->shopee_account = $request->shopee_account;
        $user_shopee->save();

        return redirect()->route('Admin.users.detail', $customer->user_id)->with('success', 'Customer Updated');
    }
}

resources/views/admin/user/add.blade.php
@include('admin.components.header')
@include('admin.components.navbar')
@include('admin.components.sidebar')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Add Account</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('Admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('Admin.users.index') }}">User Management</a></li>
                        <li class="breadcrumb-item active">Add Account</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <form action="{{ route('Admin.users.store') }}" method="POST">
                    @csrf
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input type="text"
                                        class="form-control {{ $errors->has('username') ? 'is-invalid' : '' }}"
                                        name="username" id="username" placeholder="Enter username"
                                        value="{{ old('username') }}">
                                    @if ($errors->has('username'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('username') }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    <div class="input-group date">
                                        <input type="password"
                                            class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}"
                                            name="password" id="password" placeholder="Password">
                                        <div class="input-group-append" id="togglePassword">
                                            <div class="input-group-text"><i id="eye" style="cursor: pointer"
                                                    class="fas fa-eye-slash"></i></div>
                                        </div>
                                        @if ($errors->has('password'))
                                            <div class="invalid-feedback">
                                                {{ $errors->first('password') }}
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="jumlah_user">Total Activation Account</label>
                            <input type="number" min=1
                                class="form-control {{ $errors->has('jumlah_user') ? 'is-invalid' : '' }}"
                                name="jumlah_user" id="jumlah_user" placeholder="Enter username" value="1">
                            @if ($errors->has('jumlah_user'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('jumlah_user') }}
                                </div>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="expiredate">Expired Date</label>
                            <div class="input-group date" id="expiredate" data-target-input="nearest">
                                <input type="text"
                                    class="form-control datetimepicker-input {{ $errors->has('expiredate') ? 'is-invalid' : '' }}"
                                    name="expiredate" data-target="#expiredate" data-toggle="datetimepicker" />
                                <div class="input-group-append" data-target="#expiredate" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                                @if ($errors->has('expiredate'))
                                    <div class="invalid-feedback">
                                        {{ $errors->first('expiredate') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="d-block px-4 mb-4">
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </div>
                </form>
            </div>

        </div>
        <!--/. container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- Date -->
@include('admin.components.footer')

resources/views/admin/user/detail.blade.php
@include('admin.components.header')
@include('admin.components.navbar')
@include('admin.components.sidebar')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Detail User {{ $customer->username }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('Admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('Admin.users.index') }}">User
                                Management</a></li>
                        <li class="breadcrumb-item active">Detail User Management</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    @if (Session::has('success'))
        <div class="mx-4">
            <div class="alert alert-success">
                {{ Session::get('success') }}
                @php
                    Session::forget('success');
                @endphp
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="mx-4">
            <div class="alert alert-danger">
                {{ Session::get('error') }}
                @php
                    Session::forget('error');
                @endphp
            </div>
        </div>
    @endif
    <!-- /.content-header -->
    <div class="card mx-3">
        <div class="card-header">
            <a href="{{ route('Admin.users_shopee.create_account', $customer->user_id) }}" class="btn btn-primary"><i
                    class="fas fa-user-plus mr-1"></i> Add
                Shopee Account</a>
        </div>
        <div class="card-body px-2 pb-2">
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-hover" data-id="{{ $customer->user_id }}"
                                id="datatable_shopee_account">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>#</th>
                                        <th>Shopee Account</th>
                                        <th>ACTION</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
@include('admin.components.footer')

resources/views/admin/user/edit.blade.php
@include('admin.components.header')
@include('admin.components.navbar')
@include('admin.components.sidebar')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Edit Account</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('Admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('Admin.users.index') }}">User Management</a></li>
                        <li class="breadcrumb-item active">Edit Account</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <form action="{{ route('Admin.users.update', $user_data->user_id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input type="text" readonly
                                        class="form-control {{ $errors->has('username') ? 'is-invalid' : '' }}"
                                        name="username" id="username" placeholder="Enter username"
                                        value="{{ $user_data->username }}">
                                    @if ($errors->has('username'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('username') }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="editdate">Expired Date</label>
                                    <div class="input-group date" id="editdate" data-target-input="nearest">
                                        <input type="text"
                                            class="form-control datetimepicker-input {{ $errors->has('editdate') ? 'is-invalid' : '' }}"
                                            name="editdate" data-target="#editdate" data-toggle="datetimepicker" />
                                        <div class="input-group-append" data-target="#editdate"
                                            data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                        @if ($errors->has('editdate'))
                                            <div class="invalid-feedback">
                                                {{ $errors->first('editdate') }}
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="username">Total Activation Account</label>
                            <input type="number" min=1
                                class="form-control {{ $errors->has('jumlah_user') ? 'is-invalid' : '' }}"
                                name="jumlah_user" id="jumlah_user" placeholder="Enter username"
                                value="{{ $user_data->jumlah_user }}">
                            @if ($errors->has('jumlah_user'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('jumlah_user') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="d-block px-4 mb-4">
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </div>
                </form>
            </div>

        </div>
        <!--/. container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- Date -->
@include('admin.components.footer')

resources/views/admin/user/index.blade.php
@include('admin.components.header')
@include('admin.components.navbar')
@include('admin.components.sidebar')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">User Management</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('Admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">User Management</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    @if (Session::has('success'))
        <div class="mx-4">
            <div class="alert alert-success">
                {{ Session::get('success') }}
                @php
                    Session::forget('success');
                @endphp
            </div>
        </div>
    @endif
    <!-- /.content-header -->
    <div class="card mx-3">
        <div class="card-header">
            <a href="{{ route('Admin.users.add') }}" class="btn btn-primary"><i class="fas fa-user-plus mr-1"></i> Add
                Account</a>
        </div>
        <div class="card-body px-2 pb-2">
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-hover" id="datatable">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>#</th>
                                        <th>USERNAME</th>
                                        <th>Activation Account</th>
                                        <th>CREATED AT</th>
                                        <th>EXPIRED DATE</th>
                                        <th>STATUS</th>
                                        <th>ACTION</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
@include('admin.components.footer')