routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\CustomerController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::namespace('Admin')->group(function () {
    Route::group(['middleware' => 'auth', 'prefix' => 'Admin', 'as' => 'Admin.'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

        #User
        Route::get('/users', 'UserController@index')->name('users.index');
        Route::get('/users/add', 'UserController@create')->name('users.add');
        Route::post('/users/store', 'UserController@store')->name('users.store');
        Route::get('/users/edit/{id}', 'UserController@edit')->name('users.edit');
        Route::put('/users/update/{id}', 'UserController@update')->name('users.update');
        Route::get('/users/detail/{id}', 'UserController@show')->name('users.detail');
        Route::delete('/users/delete/{id}', 'UserController@destroy')->name('users.destroy');


        #account shopee
        Route::get('/user-shopee/add/{id}', 'UserController@create_account')->name('users_shopee.create_account');
        Route::post('/user-shopee/store', 'UserController@store_account')->name('users_shopee.store_account');
        Route::delete('/user-shopee/destroy/{id}', 'UserController@destroy_account')->name('users_shopee.destroy_account');
        Route::get('/user-shopee/edit/{id}', 'UserController@edit_account')->name('users_shopee.edit_account');
        Route::put('/user-shopee/update/{id}', 'UserController@update_account')->name('users_shopee.update_account');
    });
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/components/footer.blade.php
 <!-- Control Sidebar -->
 <aside class="control-sidebar control-sidebar-dark">
     <!-- Control sidebar content goes here -->
 </aside>
 <!-- /.control-sidebar -->
 <!-- Main Footer -->
 <footer class="main-footer">
     {{-- <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved. --}}
     <div class="float-right d-none d-sm-inline-block">
         <b>Version</b> 0.0.1
     </div>
 </footer>
 </div>
 <!-- ./wrapper -->
 <!-- REQUIRED SCRIPTS -->
 <!-- jQuery -->
 <script src="{{ asset('assets/plugins/jquery/jquery.min.js') }}"></script>
 <!-- Bootstrap -->
 <script src="{{ asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
 <!-- overlayScrollbars -->
 <script src="{{ asset('assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
 <!-- AdminLTE App -->
 <script src="{{ asset('assets/dist/js/adminlte.js') }}"></script>
 <!-- DataTables  & Plugins -->
 <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
 <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
 <script src="https://cdn.datatables.net/autofill/2.3.7/js/dataTables.autoFill.min.js"></script>
 <script src="https://cdn.datatables.net/autofill/2.3.7/js/autoFill.bootstrap4.min.js"></script>
 <!-- InputMask -->
 <script src="{{ asset('assets/plugins/moment/moment.min.js') }}"></script>
 <!-- Tempusdominus Bootstrap 4 -->
 <script src="{{ asset('assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>

 <script type="text/javascript">
     $(document).ready(function() {
         $('#datatable').DataTable({
             processing: true,
             serverside: true,
             ajax: {
                 url: "{{ route('Admin.users.index') }}",
                 type: 'GET'
             },
             columns: [{
                     data: 'DT_RowIndex',
                     name: 'DT_RowIndex',
                     searchable: false
                 },
                 {
                     data: 'username',
                     name: 'username'
                 },
                 {
                     data: 'activationAccount',
                     name: 'activationAccount'
                 },
                 {
                     data: 'createdAt',
                     name: 'create'
                 },
                 {
                     data: 'formattedDate',
                     name: 'formattedDate'
                 },
                 {
                     data: 'status',
                     name: 'status'
                 },
                 {
                     data: 'action',
                     name: 'action',
                     orderable: false
                 }
             ],
         });

         var id = $('#datatable_shopee_account').attr("data-id");
         var url = '{{ route('Admin.users.detail', ':id') }}'
         url = url.replace(':id', id);


         $('#datatable_shopee_account').DataTable({


             processing: true,
             serverside: true,
             ajax: {
                 url: "",
                 type: 'GET'
             },
             columns: [{
                     data: 'DT_RowIndex',
                     name: 'DT_RowIndex',
                     searchable: false
                 },
                 {
                     data: 'shopee_account',
                     name: 'shopee_account'
                 },
                 {
                     data: 'action',
                     name: 'action',
                     orderable: false
                 }
             ],
         });
     })
 </script>
 <script type="text/javascript">
     function formatDate(date) {
         var d = new Date(date),
             month = '' + (d.getMonth() + 1),
             day = '' + d.getDate(),
             year = d.getFullYear();

         if (month.length < 2)
             month = '0' + month;
         if (day.length < 2)
             day = '0' + day;

         return [year, month, day].join('-');
     };


     $(function() {
         $('#expiredate').datetimepicker({
             defaultDate: Date.now(),
             minDate: Date.now(),
         });
     });


     $(function() {
         var date = "{{ isset($user_data) ? $user_data->exp_date : '' }}";
         $('#editdate').datetimepicker({
             defaultDate: formatDate(date),
             minDate: formatDate(date),
         });
     });

     const password = document.querySelector('#password');
     const eye = document.querySelector('#eye')
     const togglePassword = document.querySelector('#togglePassword');

     togglePassword?.addEventListener('click', function(e) {
         // toggle the type attribute
         const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
         password.setAttribute('type', type);
         // toggle the eye / eye slash icon
         eye.classList.toggle('fa-eye');
         if (eye.classList.contains('fa-eye')) {
             eye.classList.remove('fa-eye-slash')
         } else {
             eye.classList.add('fa-eye-slash')
         }
     });
 </script>
 </body>

 </html>

resources/views/admin/components/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin | SoperBos</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ asset('assets/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/autofill/2.3.7/css/autoFill.bootstrap4.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{ asset('assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('assets/dist/css/adminlte.min.css') }}">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{{ asset('assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">

  <!-- Preloader -->
  {{-- <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="assets/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
  </div> --}}

resources/views/admin/components/navbar.blade.php
 <!-- Navbar -->
 <nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <form method="POST" action="{{ route('logout') }}">
          @csrf
          <a class="nav-link" href="logout" onclick="event.preventDefault(); this.closest('form').submit();" role="button">
            <i class="fas fa-sign-out-alt"></i>
          </a>
        </form>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/admin/components/sidebar.blade.php
 <!-- Main Sidebar Container -->
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
     <!-- Brand Logo -->
     <a href="{{ route('Admin.dashboard') }}" class="brand-link d-flex">
         <div class="ml-3">
             <i class="fas fa-store"></i>
         </div>
         {{-- <img src="assets/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> --}}
         <span class="brand-text font-weight-light ml-2">SoperBos</span>
     </a>

     <!-- Sidebar -->
     <div class="sidebar">
         <!-- Sidebar user panel (optional) -->
         <div class="user-panel mt-3 pb-3 mb-3 d-flex">
             <div class="image">
                 <img src="{{ asset('assets/dist/img/undraw_profile.svg') }}" class="img-circle elevation-2"
                     alt="User Image">
             </div>
             <div class="info">
                 <a href="#" class="d-block">Admin</a>
             </div>
         </div>

         <!-- Sidebar Menu -->
         <nav class="mt-2">
             <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                 data-accordion="false">
                 <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                 <li class="nav-item">
                     <a href="{{ route('Admin.dashboard') }}"
                         class="nav-link {{ Request::is('dashboard') ? 'active' : '' }}">
                         <i class="nav-icon fas fa-tachometer-alt"></i>
                         <p>
                             Dashboard
                         </p>
                     </a>
                 </li>
                 <li class="nav-item {{ Request::is('users') || Request::is('add') ? 'menu-open' : '' }}">
                     <!--Request::is('others') ? 'menu-open' : -->
                     <a href="#" class="nav-link">
                         <i class="nav-icon fas fa-table"></i>
                         <p>
                             Management
                             <i class="fas fa-angle-left right"></i>
                         </p>
                     </a>
                     <ul class="nav nav-treeview">
                         <li class="nav-item">
                             <a href="{{ route('Admin.users.index') }}"
                                 class="nav-link {{ Request::is('users') || Request::is('add') ? 'active' : '' }}  ">
                                 <i class="fas fa-user-cog nav-icon"></i>
                                 <p>Users</p>
                             </a>
                         </li>
                     </ul>
                 </li>
                 <li class="nav-item">
                     <a href="#" class="nav-link">
                         <i class="nav-icon fas fa-cog"></i>
                         <p>
                             Settings
                         </p>
                     </a>
                 </li>
             </ul>
         </nav>
         <!-- /.sidebar-menu -->
     </div>
     <!-- /.sidebar -->
 </aside>