routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\CustomerController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::namespace('Admin')->group(function () {
    Route::group(['middleware' => 'auth', 'prefix' => 'Admin', 'as' => 'Admin.'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

        #User
        Route::get('/users', 'UserController@index')->name('users.index');
        Route::get('/users/add', 'UserController@create')->name('users.add');
        Route::post('/users/store', 'UserController@store')->name('users.store');
        Route::get('/users/edit/{id}', 'UserController@edit')->name('users.edit');
        Route::put('/users/update/{id}', 'UserController@update')->name('users.update');
        Route::get('/users/detail/{id}', 'UserController@show')->name('users.detail');
        Route::delete('/users/delete/{id}', 'UserController@destroy')->name('users.destroy');


        #account shopee
        Route::get('/user-shopee/add/{id}', 'UserController@create_account')->name('users_shopee.create_account');
        Route::post('/user-shopee/store', 'UserController@store_account')->name('users_shopee.store_account');
        Route::delete('/user-shopee/destroy/{id}', 'UserController@destroy_account')->name('users_shopee.destroy_account');
        Route::get('/user-shopee/edit/{id}', 'UserController@edit_account')->name('users_shopee.edit_account');
        Route::put('/user-shopee/update/{id}', 'UserController@update_account')->name('users_shopee.update_account');
    });
});

require __DIR__.'/auth.php';

resources/views/admin/account_shopee/add.blade.php
@include('admin.components.header')
@include('admin.components.navbar')
@include('admin.components.sidebar')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Add Account Shopee</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ url('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('Admin.users.detail', $customer->user_id) }}">
                                Detail
                                User Management</a></li>
                        <li class="breadcrumb-item active">Add Account</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <form action="{{ route('Admin.users_shopee.store_account') }}" method="POST">
                    @csrf
                    <div class="card-body">

                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" readonly
                                class="form-control {{ $errors->has('username') ? 'is-invalid' : '' }}"
                                name="username" id="username" placeholder="Enter username"
                                value="{{ $customer->username }}">
                            @if ($errors->has('username'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('username') }}
                                </div>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="shopee_account">Shopee Account Name</label>
                            <input type="text"
                                class="form-control {{ $errors->has('shopee_account') ? 'is-invalid' : '' }}"
                                name="shopee_account" id="shopee_account" placeholder="Enter Shopee Account Name"
                                value="" required>
                            @if ($errors->has('shopee_account'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('shopee_account') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="d-block px-4 mb-4">
                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                    </div>
                </form>
            </div>
        </div>
        <!--/. container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- Date -->
@include('admin.components.footer')

resources/views/admin/account_shopee/edit.blade.php
@include('admin.components.header')
@include('admin.components.navbar')
@include('admin.components.sidebar')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Edit Account Shopee</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('Admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('Admin.users.detail', $customer->user_id) }}">
                                Detail
                                User Management</a></li>
                        <li class="breadcrumb-item active">Add Account</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <form action="{{ route('Admin.users_shopee.update_account', $user_shopee->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="card-body">

                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" readonly
                                class="form-control {{ $errors->has('username') ? 'is-invalid' : '' }}"
                                name="username" id="username" placeholder="Enter username"
                                value="{{ $customer->username }}">
                            @if ($errors->has('username'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('username') }}
                                </div>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="shopee_account">Shopee Account Name</label>
                            <input type="text"
                                class="form-control {{ $errors->has('shopee_account') ? 'is-invalid' : '' }}"
                                name="shopee_account" id="shopee_account" placeholder="Enter Shopee Account Name"
                                value="{{ $user_shopee->shopee_account }}" required>
                            @if ($errors->has('shopee_account'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('shopee_account') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="d-block px-4 mb-4">
                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                    </div>
                </form>
            </div>
        </div>
        <!--/. container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- Date -->
@include('admin.components.footer')